services:
  fraud-detection-api:
    build: .
    container_name: fraud-detection-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=frauddetection
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fraud-net

  postgres:
    image: postgres:16-alpine
    container_name: fraud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: frauddetection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d frauddetection"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraud-net

  redis:
    image: redis:7-alpine
    container_name: fraud-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - fraud-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fraud-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraud-net

volumes:
  postgres_data:

networks:
  fraud-net:
    driver: bridge